### ISSUE TITLE
ssdCache feature not working

### ISSUE THREAD

**Issue by brunnels** [qnap-dev/QNAP-CSI-PlugIn#12] opened 2024-06-08 23:02 UTC
I'm trying to just enable ssdCache on the PVC without tiering and it seems to be ignored.  I can go into my qnap ISCSI Storage and modify the PVC after it has been created and enable ssd caching and it works.  Using latest QTS 5.1.7

Backend config:
```yaml
    - labels:
        performance: basic
      features:
        tiering: Disable
        ssdCache: "true"
      serviceLevel: basic
```

**Comment by LeonaChen2727** [comment] 2024-06-21 09:42
Hi @brunnels,

We have already identified the root cause of the issue and it fixing it now.
It will be addressed in the next version: v1.3.0.
Thanks!

**Closed** 2024-09-27 02:33 UTC
